# Generated by Django 5.2.4 on 2025-07-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
    ]
